os: osx
osx_image: xcode10.2
language: objective-c
install: true
before_install:
    - bazel_version=0.25.0
    - bazel_script=/tmp/bazel.sh
    - curl -L https://github.com/bazelbuild/bazel/releases/download/$bazel_version/bazel-$bazel_version-installer-darwin-x86_64.sh -o $bazel_script
    - chmod +x $bazel_script
    - sh $bazel_script --user
    - export PATH="$PATH:$HOME/bin"
script:
    - bazel clean --expunge
    - bazel version
    - bazel test Tests --nokeep_state_after_build --spawn_strategy=standalone --genrule_strategy=standalone --test_strategy=standalone --noshow_progress --noshow_loading_progress --verbose_failures --test_verbose_timeout_warnings --test_output=errors
