name: ci

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  spm:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  bazel:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        MODE: [ "dbg", "opt" ]
    env:
      USE_BAZEL_VERSION: 8.x
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          repository-cache: true
      - name: bazel build
        run:  |
          bazelisk build --enable_bzlmod -c "${{ matrix.MODE }}" //...
      - name: bazel test
        if: ${{ matrix.MODE == 'dbg' }}
        run:  |
          bazelisk test --enable_bzlmod --build_tests_only -c "${{ matrix.MODE }}"  --test_output=all --verbose_failures //...

  cocoapods:
    strategy:
      matrix:
        podspec: [PromisesObjC.podspec, PromisesSwift.podspec]
        platform: [ios, tvos, macos, watchos]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: |
          pod lib lint ${{ matrix.podspec }} --platforms=${{ matrix.platform }}
