name: ci

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  spm:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  cocoapods-objc:
    strategy:
      matrix:
        platform: [ios, tvos, macos, watchos]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: |
          pod lib lint PromisesObjC.podspec --platforms=${{ matrix.platform }}


  cocoapods-swift:
    strategy:
      matrix:
        platform: [ios, tvos, macos, watchos]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: |
          pod lib lint PromisesSwift.podspec --platforms=${{ matrix.platform }} --include-podspecs=PromisesObjC.podspec
